/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TeamRouteImport } from './routes/team'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamPermissionsRouteImport } from './routes/team.permissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamPermissionsRoute = TeamPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => TeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/leads': typeof LeadsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/team': typeof TeamRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/team/permissions': typeof TeamPermissionsRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/leads': typeof LeadsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/team/permissions': typeof TeamPermissionsRoute
  '/team': typeof TeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/leads': typeof LeadsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/team': typeof TeamRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/team/permissions': typeof TeamPermissionsRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/customers'
    | '/leads'
    | '/register'
    | '/settings'
    | '/sign-in'
    | '/team'
    | '/customers/$customerId'
    | '/team/permissions'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/customers'
    | '/leads'
    | '/register'
    | '/settings'
    | '/sign-in'
    | '/customers/$customerId'
    | '/team/permissions'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/customers'
    | '/leads'
    | '/register'
    | '/settings'
    | '/sign-in'
    | '/team'
    | '/customers/$customerId'
    | '/team/permissions'
    | '/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  TeamRoute: typeof TeamRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/permissions': {
      id: '/team/permissions'
      path: '/permissions'
      fullPath: '/team/permissions'
      preLoaderRoute: typeof TeamPermissionsRouteImport
      parentRoute: typeof TeamRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface TeamRouteChildren {
  TeamPermissionsRoute: typeof TeamPermissionsRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamPermissionsRoute: TeamPermissionsRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  CustomersRoute: CustomersRouteWithChildren,
  LeadsRoute: LeadsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  TeamRoute: TeamRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
