import { useEffect, useState, type ReactNode } from "react";
import { AlertCircle, CheckCircle2, Info, LoaderCircle, Search, TriangleAlert } from "lucide-react";
import { cn } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="page-enter mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div>{eyebrow&&<p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-primary">{eyebrow}</p>}<h1 className="font-display text-4xl font-medium leading-none md:text-5xl">{title}</h1>{description&&<p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</header>}
export function StatusPill({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"success"|"warning"|"danger"|"accent"}){return <span className={cn("inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold",tone==="success"&&"border-success/25 bg-success/10 text-success",tone==="warning"&&"border-warning/30 bg-warning/10 text-warning",tone==="danger"&&"border-destructive/25 bg-destructive/10 text-destructive",tone==="accent"&&"border-primary/25 bg-primary/10 text-primary",tone==="neutral"&&"border-border bg-muted text-muted-foreground")}>{children}</span>}
export function SearchField({value,onChange,placeholder="Search"}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="pl-9"/></div>}
export function AnimatedNumber({value,prefix="",suffix=""}:{value:number;prefix?:string;suffix?:string}){const [shown,setShown]=useState(0);useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setShown(value);return}let frame=0;const total=36;const timer=window.setInterval(()=>{frame+=1;setShown(Math.round(value*(frame/total)));if(frame>=total)window.clearInterval(timer)},22);return()=>window.clearInterval(timer)},[value]);return <span className="tabular-nums">{prefix}{shown.toLocaleString()}{suffix}</span>}
export function StatCard({label,value,delta,icon}:{label:string;value:ReactNode;delta:string;icon:ReactNode}){return <Card className="reveal-card group p-5 transition-transform hover:-translate-y-1"><div className="flex items-start justify-between"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">{label}</p><span className="grid size-8 place-items-center rounded-full bg-secondary text-primary">{icon}</span></div><div className="mt-7 font-display text-4xl leading-none">{value}</div><p className="mt-3 text-xs text-muted-foreground"><span className="font-semibold text-success">{delta}</span> from last month</p></Card>}
export function Banner({tone,title,children}:{tone:"info"|"success"|"warning"|"error";title:string;children:ReactNode}){const Icon=tone==="success"?CheckCircle2:tone==="warning"?TriangleAlert:tone==="error"?AlertCircle:Info;return <div className={cn("flex gap-3 rounded-md border p-4",tone==="info"&&"border-info/25 bg-info/10",tone==="success"&&"border-success/25 bg-success/10",tone==="warning"&&"border-warning/25 bg-warning/10",tone==="error"&&"border-destructive/25 bg-destructive/10")}><Icon className="mt-0.5 size-4 shrink-0"/><div><p className="text-sm font-semibold">{title}</p><div className="mt-1 text-xs leading-5 text-muted-foreground">{children}</div></div></div>}
export function EmptyState({icon,title,description,action}:{icon:ReactNode;title:string;description:string;action?:ReactNode}){return <div className="grid min-h-56 place-items-center border border-dashed border-border p-8 text-center"><div><div className="mx-auto grid size-10 place-items-center rounded-full bg-secondary text-muted-foreground">{icon}</div><h3 className="mt-4 font-display text-xl">{title}</h3><p className="mt-2 max-w-sm text-sm text-muted-foreground">{description}</p>{action&&<div className="mt-5">{action}</div>}</div></div>}
export function FullPageLoader(){return <div className="grid min-h-[60vh] place-items-center"><div className="text-center"><LoaderCircle className="mx-auto size-7 animate-spin text-primary"/><p className="mt-3 font-display text-lg">Preparing your workspace</p></div></div>}
